version: '3.4'
services:
  electricflow:
    image: "electricflow/efserver:latest"
    ports:
      - "8000:8000"
      - "8200:8200"
      - "8443:8443"
      - "443:443"
      - "80:80"
    networks:
      - internal
    container_name: electricflow
    hostname: electricflow
    tty: true
    environment:
      - COMMANDER_SERVER=electricflow
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/rest/v1.0/server/info"]
      interval: 120s
      timeout: 10s
      retries: 3
      start_period: 120s
    restart: always

  # Needed to restart failed EF
  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  weblogic:
    image: electricflow/weblogic:12.2.1.3
    ports:
      - "7001:7001"
      - "7808:7808"
    networks:
      - internal
    container_name: weblogic
    tty: true
    environment:
      - COMMANDER_SERVER=electricflow
      - PRODUCTION_MODE=prod

  mysql:
    image: mysql:5.7
    container_name: mysql
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=customers_db
    ports:
      - "3308:3306"

networks:
  internal:
    driver: bridge
