version: '3'
services:
  electricflow:
    image: "electricflow/efserver"
    ports:
      - "8000:8000"
      - "8200:8200"
      - "8443:8443"
      - "443:443"
      - "80:80"
    networks:
      - internal
    container_name: electricflow
    hostname: electricflow
    tty: true
    environment:
      - COMMANDER_SERVER=electricflow
    healthcheck:
      test: ["CMD", "curl", "-f", "curl http://localhost:8000/rest/v1.0/server/info"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  weblogic:
    image: electricflow/weblogic:12.2.1.3-generic
    ports:
      - "7001:7001"
      - "7808:7808"
    networks:
      - internal
    container_name: weblogic
    tty: true
    environment:
      - COMMANDER_SERVER=electricflow
      - PRODUCTION_MODE=prod
networks:
  internal:
    driver: bridge
